version: "3.9"

services:
  blaze:
    image: "samply/blaze:0.21"
    environment:
      BASE_URL: "http://localhost:8091"
      #BASE_URL: "http://blaze:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      ENFORCE_REFERENTIAL_INTEGRITY: "false"
    ports:
      - "8091:8080"
    volumes:
      - "blaze-mitro-069:/app/data"
    networks:
      - teiler-ui

networks:
  teiler-ui:
    name: "teiler-ui"

volumes:
  blaze-mitro-069:
    name: "blaze-mitro-069"
